### ISSUE TITLE
MD Formatting in Prompt

### ISSUE THREAD

**Issue by moritztim** [vscode-reborn-ai/vscode-reborn-ai#62]
### Describe the feature

Allow for optional markdown formatting in the prompt and render newlines by default.

Example prompt with newlines:
![Prompt](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/b41ef23a-87c5-4a9e-9451-4d0b46bc4798)
In edit mode:
![Edit mode](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/90388353/b69c8f33-56bc-41a8-83db-d75874aeb9ba)

**Comment by Christopher-Hayes** [comment]
Thanks @moritz-t-w, yeah I've been meaning to add a toggle for this.

**Comment by Christopher-Hayes** [comment]
The newlines not rendering seems like a bug, so that will be fixed in the next release.

I'm not sure yet if we want markdown formatting for the user question, the trouble is if the user pastes some code in their question, markdown formatting will try to render it. I think at one point we _did_ render markdown in the user question, but asking a question about a <table> would show a table, so that was disabled.

However, in relation to a markdown toggle, the next release will have a toggle for markdown formatting of the ai responses.
