### ISSUE TITLE
Duplicate and Redundant Model Names in the Model Options

### ISSUE THREAD

**Issue by PeterDaveHello** [vscode-reborn-ai/vscode-reborn-ai#83]
In the model selection dropdown menu, there are duplicated and redundant model names, which seem unnecessary and unclear in their purpose.

Screenshot:
![image](https://github.com/Christopher-Hayes/vscode-chatgpt-reborn/assets/3691490/1b5374da-5a3b-4d2a-a3be-bc81bf43aa18)

**Comment by PeterDaveHello** [comment]
Is this related to any commit?

**Comment by Christopher-Hayes** [comment]
> Is this related to any commit?

Are the competion models still showing for you? I just pulled up the dev instance, and didn't see the models, so I marked it done.

I'm checking the git blame now, and maybe this is related to the translation files because package.json seems like it hasn't had those models in the enum list since at least last year.

**Comment by Christopher-Hayes** [comment]
@coderabbitai can you check translation files values with the key "chatgpt.gpt3.model.*", to see if any of them contain any of the following models?

```
text-davinci-003
text-curie-001
text-babbage-001
text-ada-001
code-davinci-002
code-cushman-001
```

The English version has these models, which are allowed.

```
    "chatgpt.gpt3.model.enumItemLabels1": "OpenAI API Key - gpt-4-turbo",
    "chatgpt.gpt3.model.enumItemLabels2": "OpenAI API Key - gpt-4",
    "chatgpt.gpt3.model.enumItemLabels3": "OpenAI API Key - gpt-3.5-turbo",
    "chatgpt.gpt3.model.enumItemLabels4": "OpenAI API Key - gpt-3.5-turbo-16k",
```

**Comment by Christopher-Hayes** [comment]
Ohh @PeterDaveHello this issue was more about the dropdown showing "gpt-4 gpt-4", when it should be showing something like "OpenAI GPT-4 gpt-4"? I see now.

@coderabbitai so the situation is the label on the enums for this model dropdown is showing the same exact text as the enum value. How do we fix this issue? It's both in the package.json as well as has translation file overrides. The enum description is definitely working fine, it's just the label that is not working.

**Comment by PeterDaveHello** [comment]
@Christopher-Hayes I think it should be just "OpenAI GPT-4"

**Comment by Christopher-Hayes** [comment]
> @Christopher-Hayes I think it should be just "OpenAI GPT-4"

They're enums, so VS Code's UI will show the enum "value". If we didn't have the "labels", it would only show the value. I don't believe there's a way to have it only show the label, but not the value.

**Comment by PeterDaveHello** [comment]
hmmm ... I didn't think about the implementation, but from the view of a user, that's a little bit confusing.

**Comment by Christopher-Hayes** [comment]
> hmmm ... I didn't think about the implementation, but from the view of a user, that's a little bit confusing.

Our options are either no labels:

```
gpt-4o
gpt-4o-mini
[...]
```

or with labels:

```
OpenAI GPT-4o   gpt-4o
OpenAI GPT-4o Mini   gpt-4o-mini
[...]
```

Regardless, we shouldn't spend much time on this. Next release I think we might just remove this model dropdown all together because users are finding it confusing when they use a custom (non-OpenAI) model, and this config setting only gives OpenAI models.

**Comment by PeterDaveHello** [comment]
another implementation that'll just by pass this issue will be great, then we can just ignore this issue right now 👍
